version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    ports:
      # デバック用でrethinkdbの管理画面を表示するために8080ポートを開放
      - "8080:8080"
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

#  adb:
#    container_name: adb
#    image: devicefarmer/adb:latest
#    restart: unless-stopped
#    volumes:
#      - "/dev/bus/usb:/dev/bus/usb"
#    privileged: true

  stf:
    container_name: stf
    image: devicefarmer/stf
    ports:
      - "7100:7100"
      # WebSocket用ポート
      - "7110:7110"
      # Androidデバイス用ポート
      - "7400-7500:7400-7500"
    environment:
      - TZ='Asia/Tokyo'
      # migrate時に環境変数でRethinkDBのURLが必要なため指定
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
    restart: unless-stopped
    # adb-hostでhost.docker.internalを指定し、adbコンテナを使わずにローカルインストールされたadbを使う
    command: stf local --adb-host host.docker.internal --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
